
Style/Documentation:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Security/YAMLLoad:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'